// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>


#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192

using System.Collections.Generic;
using ProtoBuf;

namespace MRL.SSL.Common.SSLWrapperCommunication
{
    [ProtoContract(Name = @"SSL_DetectionBall")]
    public partial class SSLDetectionBall : IExtensible
    {
        private IExtension __pbn__extensionData;
        IExtension IExtensible.GetExtensionObject(bool createIfMissing)
            => Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [ProtoMember(1, Name = @"confidence", IsRequired = true)]
        public float Confidence { get; set; }

        [ProtoMember(2, Name = @"area")]
        public uint Area
        {
            get => __pbn__Area.GetValueOrDefault();
            set => __pbn__Area = value;
        }
        public bool ShouldSerializeArea() => __pbn__Area != null;
        public void ResetArea() => __pbn__Area = null;
        private uint? __pbn__Area;

        [ProtoMember(3, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [ProtoMember(4, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

        [ProtoMember(5, Name = @"z")]
        public float Z
        {
            get => __pbn__Z.GetValueOrDefault();
            set => __pbn__Z = value;
        }
        public bool ShouldSerializeZ() => __pbn__Z != null;
        public void ResetZ() => __pbn__Z = null;
        private float? __pbn__Z;

        [ProtoMember(6, Name = @"pixel_x", IsRequired = true)]
        public float PixelX { get; set; }

        [ProtoMember(7, Name = @"pixel_y", IsRequired = true)]
        public float PixelY { get; set; }

    }

    [ProtoContract(Name = @"SSL_DetectionRobot")]
    public partial class SSLDetectionRobot : IExtensible
    {
        private IExtension __pbn__extensionData;
        IExtension IExtensible.GetExtensionObject(bool createIfMissing)
            => Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [ProtoMember(1, Name = @"confidence", IsRequired = true)]
        public float Confidence { get; set; }

        [ProtoMember(2, Name = @"robot_id")]
        public uint? Id
        {
            get => __pbn__RobotId;
            set => __pbn__RobotId = value;
        }
        public bool ShouldSerializeRobotId() => __pbn__RobotId != null;
        public void ResetRobotId() => __pbn__RobotId = null;
        private uint? __pbn__RobotId;

        [ProtoMember(3, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [ProtoMember(4, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

        [ProtoMember(5, Name = @"orientation")]
        public float? Orientation
        {
            get => __pbn__Orientation;
            set => __pbn__Orientation = value;
        }
        public bool ShouldSerializeOrientation() => __pbn__Orientation != null;
        public void ResetOrientation() => __pbn__Orientation = null;
        private float? __pbn__Orientation;

        [ProtoMember(6, Name = @"pixel_x", IsRequired = true)]
        public float PixelX { get; set; }

        [ProtoMember(7, Name = @"pixel_y", IsRequired = true)]
        public float PixelY { get; set; }

        [ProtoMember(8, Name = @"height")]
        public float Height
        {
            get => __pbn__Height.GetValueOrDefault();
            set => __pbn__Height = value;
        }
        public bool ShouldSerializeHeight() => __pbn__Height != null;
        public void ResetHeight() => __pbn__Height = null;
        private float? __pbn__Height;

    }

    [ProtoContract(Name = @"SSL_DetectionFrame")]
    public partial class SSLDetectionFrame : IExtensible
    {
        private IExtension __pbn__extensionData;
        IExtension IExtensible.GetExtensionObject(bool createIfMissing)
            => Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [ProtoMember(1, Name = @"frame_number", IsRequired = true)]
        public uint FrameNumber { get; set; }

        [ProtoMember(2, Name = @"t_capture", IsRequired = true)]
        public double CaptureTime { get; set; }

        [ProtoMember(3, Name = @"t_sent", IsRequired = true)]
        public double SentTime { get; set; }

        [ProtoMember(4, Name = @"camera_id", IsRequired = true)]
        public uint CameraId { get; set; }

        [ProtoMember(5, Name = @"balls")]
        public List<SSLDetectionBall> Balls { get; } = new List<SSLDetectionBall>();

        [ProtoMember(6, Name = @"robots_yellow")]
        public List<SSLDetectionRobot> YellowRobots { get; } = new List<SSLDetectionRobot>();

        [ProtoMember(7, Name = @"robots_blue")]
        public List<SSLDetectionRobot> BlueRobots { get; } = new List<SSLDetectionRobot>();

    }
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion